-- 1. Provide an overview of all freelancers and their hourly price, daily price (8hours) and their address info (including state, zip, ...) ordered by price

SELECT
  FREELANCERS.FREELANCER_ID,
  FREELANCERS.NAME,
  FREELANCERS.PRICE,
  FREELANCERS.PRICE * 8 AS "Price per day",
  FREELANCERS.ADDRESS,
  FREELANCERS.ZIPCODE,
  ZIPCODES.CITY,
  ZIPCODES.COUNTY,
  ZIPCODES.STATE
FROM web.FREELANCERS
  JOIN web.ZIPCODES ON FREELANCERS.ZIPCODE = ZIPCODES.ZIPCODE
ORDER BY price DESC;

-- 2. Provide an overview of all projects (ID, Name) and their customers (including address info)
SELECT
  PROJECTS.PROJECT_ID,
  PROJECTS.PROJECT_NAME,
  CUSTOMERS.CUSTOMER_NAME,
  CUSTOMERS.ADDRESS,
  CUSTOMERS.ZIPCODE,
  ZIPCODES.CITY,
  ZIPCODES.COUNTY,
  ZIPCODES.STATE
FROM WEB.PROJECTS
  JOIN WEB.CUSTOMERS ON PROJECTS.CUSTOMER_ID = CUSTOMERS.CUSTOMER_ID
  JOIN WEB.ZIPCODES ON CUSTOMERS.ZIPCODE = ZIPCODES.ZIPCODE;

--  3. Provide an overview of all worklogs (date and hours, days (8h)), including freelancer name and project name
SELECT
  FREELANCERS.NAME,
  WORKLOGS.WORKDAY,
  WORKLOGS.HOURS,
  WORKLOGS.HOURS / 8 AS "DAYS",
  PROJECTS.PROJECT_NAME
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
  JOIN web.PROJECTS ON WORKLOGS.PROJECT_ID = PROJECTS.PROJECT_ID;

--  4. Provide an overview of all projects, their estimation and the amount of days actually spent
SELECT
  PROJECTS.PROJECT_ID,
  PROJECTS.PROJECT_NAME,
  PROJECTS.ESTIMATION,
  sum(WORKLOGS.HOURS) / 8 AS "DAYS"
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
  JOIN web.PROJECTS ON WORKLOGS.PROJECT_ID = PROJECTS.PROJECT_ID
GROUP BY PROJECTS.PROJECT_ID, PROJECT_NAME, ESTIMATION;

-- 5. Provide an overview of all projects, their estimation, the amount of days spent and the over/underspent in percentage

SELECT
  PROJECTS.PROJECT_ID,
  PROJECTS.PROJECT_NAME,
  PROJECTS.ESTIMATION,
  sum(WORKLOGS.HOURS) / 8                        AS "DAYS",
  ((sum(WORKLOGS.HOURS) / 8) / ESTIMATION) * 100 AS "Over/underspent %"
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
  JOIN web.PROJECTS ON WORKLOGS.PROJECT_ID = PROJECTS.PROJECT_ID
GROUP BY PROJECTS.PROJECT_ID, PROJECT_NAME, ESTIMATION;

-- 6. Provide an overview of all projects, and their actual cost (payed to freelancers)

SELECT
  PROJECT_NAME,
  sum(PRICE * HOURS)
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
  JOIN web.PROJECTS ON WORKLOGS.PROJECT_ID = PROJECTS.PROJECT_ID
GROUP BY PROJECT_NAME;

-- 7. calculate the average freelance price

SELECT avg(PRICE)
FROM WEB.FREELANCERS;

-- 8. Provide an overview of all projects, their estimation, and income based on: estimation * (average hourly freelance price + 10% margin) *8

SELECT
  PROJECT_ID,
  PROJECT_NAME,
  ESTIMATION,
  ESTIMATION * (SELECT avg(PRICE) * 1.1
                FROM WEB.FREELANCERS) * 8
FROM WEB.PROJECTS;

-- 9. Provide an overview of all freelancers and their total time spent on all projects in days


SELECT
  FREELANCERS.FREELANCER_ID,
  FREELANCERS.NAME,
  sum(HOURS) / 8
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
GROUP BY FREELANCERS.FREELANCER_ID, FREELANCERS.NAME;


-- 10. Provide an overview of all freelancers, their price (day), days worked and total earnings

SELECT
  FREELANCERS.FREELANCER_ID,
  FREELANCERS.NAME,
  FREELANCERS.PRICE * 8,
  sum(hours) / 8,
  sum(HOURS * price)
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
GROUP BY FREELANCERS.FREELANCER_ID, FREELANCERS.NAME, FREELANCERS.PRICE;

-- 11. Provide an overview of all worklogs (freelancer, date, year, month, hours spent and project)

SELECT
  FREELANCERS.NAME,
  WORKLOGS.WORKDAY,
  EXTRACT(YEAR FROM WORKLOGS.WORKDAY)  AS "YEAR",
  EXTRACT(MONTH FROM WORKLOGS.WORKDAY) AS "MONTH",
  WORKLOGS.HOURS,
  PROJECTS.PROJECT_NAME
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
  JOIN web.PROJECTS ON WORKLOGS.PROJECT_ID = PROJECTS.PROJECT_ID;

--12. Provide an overview of all worklogs from April 2017  (freelancer, date, year, month, hours spent and project)

SELECT
  FREELANCERS.NAME,
  WORKLOGS.WORKDAY,
  EXTRACT(YEAR FROM WORKLOGS.WORKDAY)  AS "YEAR",
  EXTRACT(MONTH FROM WORKLOGS.WORKDAY) AS "MONTH",
  WORKLOGS.HOURS,
  PROJECTS.PROJECT_NAME
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
  JOIN web.PROJECTS ON WORKLOGS.PROJECT_ID = PROJECTS.PROJECT_ID
WHERE EXTRACT(YEAR FROM WORKLOGS.WORKDAY) = 2017 AND
      EXTRACT(MONTH FROM WORKLOGS.WORKDAY) = 4;

--13. Provide an overview of all days spent per month

SELECT
  EXTRACT(YEAR FROM WORKLOGS.WORKDAY)  AS "YEAR",
  EXTRACT(MONTH FROM WORKLOGS.WORKDAY) AS "MONTH",
  sum(hours / 8)
FROM WEB.WORKLOGS
GROUP BY
  EXTRACT(YEAR FROM WORKLOGS.WORKDAY),
  EXTRACT(MONTH FROM WORKLOGS.WORKDAY)
ORDER BY EXTRACT(YEAR FROM WORKLOGS.WORKDAY),
  EXTRACT(MONTH FROM WORKLOGS.WORKDAY) ASC;

-- 14. Provide an overview of al zipcodes of: freelancers with a hourly rate higher than 50 and zipcodes of projects with an "u" in their name

SELECT zipcode
FROM freelancers
WHERE price > 50
UNION
SELECT zipcode
FROM customers
WHERE lower(customer_name) LIKE '%u%';

-- 15. Provide an overview of states for which we have both freelancers and customers

SELECT STATE
FROM freelancers
  JOIN ZIPCODES ON FREELANCERS.ZIPCODE = ZIPCODES.ZIPCODE
INTERSECT
SELECT STATE
FROM customers
  JOIN ZIPCODES ON CUSTOMERS.ZIPCODE = ZIPCODES.ZIPCODE;


SELECT STATE
FROM freelancers
  JOIN ZIPCODES ON FREELANCERS.ZIPCODE = ZIPCODES.ZIPCODE
WHERE STATE IN (
  SELECT STATE
  FROM customers
    JOIN ZIPCODES ON CUSTOMERS.ZIPCODE = ZIPCODES.ZIPCODE
);

-- 16. provide an overview of all days spent, per freelancer per project

SELECT
  PROJECTS.PROJECT_NAME,
  FREELANCERS.NAME,
  sum(WORKLOGS.HOURS) / 8
FROM WEB.WORKLOGS
  JOIN WEB.FREELANCERS ON WORKLOGS.FREELANCER_ID = FREELANCERS.FREELANCER_ID
  JOIN web.PROJECTS ON WORKLOGS.PROJECT_ID = PROJECTS.PROJECT_ID
GROUP BY FREELANCERS.NAME, PROJECTS.PROJECT_NAME
ORDER BY PROJECT_NAME, NAME;

