CREATE DATABASE [BILLING]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BILLING', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BILLING.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BILLING_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BILLING_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BILLING] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [BILLING] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BILLING] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BILLING] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BILLING] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BILLING] SET ARITHABORT OFF 
GO
ALTER DATABASE [BILLING] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BILLING] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BILLING] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [BILLING] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BILLING] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BILLING] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BILLING] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BILLING] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BILLING] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BILLING] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BILLING] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BILLING] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BILLING] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BILLING] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BILLING] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BILLING] SET  READ_WRITE 
GO
ALTER DATABASE [BILLING] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BILLING] SET  MULTI_USER 
GO
ALTER DATABASE [BILLING] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BILLING] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BILLING] SET DELAYED_DURABILITY = DISABLED 
GO
USE [BILLING]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [BILLING]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [BILLING] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO



CREATE LOGIN [billing_owner] WITH PASSWORD='password', 
DEFAULT_DATABASE=[BILLING], 
DEFAULT_LANGUAGE=[us_english], 
CHECK_EXPIRATION=OFF,
CHECK_POLICY=OFF
GO


USE [BILLING]
CREATE USER [billing_owner] FOR LOGIN [billing_owner]
ALTER ROLE [db_owner] ADD MEMBER [billing_owner]
GO


/*
Drop login, drop connections, drop database
*/
DROP LOGIN [billing_owner]
ALTER DATABASE [BILLING] SET  SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE [BILLING] 
GO



